### ISSUE TITLE
Masif_pymol_plugin erorr

### ISSUE THREAD

**Issue by abbynewbury** [LPDI-EPFL/masif#11]
Hi,

I am able to install the masaif_pymol_plugin into pymol but when I try to load the plugin pymol gives me this error:
Unable to initialize plugin 'masif_pymol_plugin' (pmg_tk.startup.masif_pymol_plugin).

I tried writing "import pmg_tk.startup.masif_pymol_plugin" in the pymol command line as well but it gives me an error again:
Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pmg_tk/startup/masif_pymol_plugin/__init__.py", line 5, in <module>
    from loadPLY import *
ModuleNotFoundError: No module named 'loadPLY'

I also looked in the masif_pymol_plugin folder to make sure there was a loadPLY file and there was.
Thank you!

**Comment by pablogainza** [comment]
Hi ! Sorry about this. Please take a look here: https://github.com/LPDI-EPFL/masif/issues/15
