### ISSUE TITLE
How to install reduce(3.23)

### ISSUE THREAD

**Issue by zshyang** [LPDI-EPFL/masif#14]
Hi, 
Thanks for your great work. I was trying to install dependencies. But I am not sure how to install reduce(3.23) on the Linux system.
Could you show me how?

**Comment by pablogainza** [comment]
So reduce is super easy to install. You just need to download the linux executable from 
http://kinemage.biochem.duke.edu/software/reduce.php. 
You need to download the executable for linux, gunzip it, add executable permissions and then just run that program.

**Comment by zshyang** [comment]
Thank you very much. I also checked the docker file you provided. And it is also quite clear there.

**Comment by ELMIAR-0642** [comment]
reduce could not be installed. Page not found http://kinemage.biochem.duke.edu/software/reduce.php.
