### ISSUE TITLE
The provide docker file do not support tensorflow GPU

### ISSUE THREAD

**Issue by zshyang** [LPDI-EPFL/masif#16]
Hi,
Thanks for sharing this great work. But the docker file you provided seems do not have the GPU included.
Do you know how could I include GPU and TensorFlow-GPU into the docker image?
Best regards!

**Comment by pablogainza** [comment]
Hi! So I'm not sure how to include these - I've never run it. Did you try this tutorial?
https://www.tensorflow.org/install/docker

**Comment by zshyang** [comment]
Thanks for your reply. I did not try the tutorial.
And It seems that the docker you provided is only for data processing.
Once the data processing is done. I could use some virtual environment with TensorFlow installed. 
Do I understand correctly?

**Comment by pablogainza** [comment]
So I think that should work yes.
