### ISSUE TITLE
Patch extraction

### ISSUE THREAD

**Issue by LivC182** [LPDI-EPFL/masif#2]
Sorry to bother you, I don't really understand how you divide the mesh surface into patches. 

Do you start at one random vertex in the mesh, perform geodesic distance calculation for a given radius, select new vertex that is yet to be parsed in previous calculations or just compute patches for each vertex in the mesh? Input for neural network consists a matrix of size: number of patches x features considered (5)

I cannot find the code lines that explain this patch division.

Best,
Liv

**Comment by FreyrS** [comment]
Hi Liv
The patches are computed for every vertex in the mesh.
They are extracted during the precomputation under source/matlab_libs/coords_mds.m.
Let us know if you have any further questions!
