### ISSUE TITLE
Missing lower bound in normalize_electrostatics

### ISSUE THREAD

**Issue by vsomnath** [LPDI-EPFL/masif#20]
Hi, 

Thank you for this great repository, it has been very useful so far. Working with it, I noticed an issue as highlighted below in the following function:

https://github.com/LPDI-EPFL/masif/blob/0657ec97cf9a0162988e172d08376f459f0f8689/source/masif_modules/read_data_from_surface.py#L251

The electrostatics are upper-bounded to 3, but not lower-bounded to -3. I don't think this was intentional.

**Comment by pablogainza** [comment]
Dear vsomnath, 

Sorry for the late reply! 

Indeed this is  a bug! I think the impact shouldn't be too large, because the magnitude of the values was already decreased by a factor of 10, but I will retrain just in case to see if it changes a lot.

Thank you very much!!
