### ISSUE TITLE
Error handling: missing atoms when calculating hydrogen-bonding potential

### ISSUE THREAD

**Issue by jomimc** [LPDI-EPFL/masif#28]
Sometimes I've found that when looking for hydrogen bond acceptors, the code will break if the acceptor atom is there but coordinates are missing for its bonded, neighbouring atom. I.e. in "triangulation.computeCharges" line 82, res[acceptorAngleAtom[atom_name]].get_coord() will throw a KeyError exception. I found this on PDB entries 2avn and 1vdn.

My suggested fix was already implemented for acceptorPlaneAtom in the same function:

```
try:
    a = res[acceptor_atom.get_coord()
except KeyError:
    return 0.0
```

**Comment by pablogainza** [comment]
Thank you !!! I've fixed this, as suggested.
