### ISSUE TITLE
how to visualize the output files?

### ISSUE THREAD

**Issue by jh4yd** [LPDI-EPFL/masif#43]
The pdl1_benchmark_nn.py produces several .pdb files and .vert files. Just wondering use these files, say to visualize the docking site in PyMol? Thank you.

**Comment by jh4yd** [comment]
wrote a small pymesh script, problem is solved.

**Comment by xiaolinpan** [comment]
I also want to visualize the output of MaSIF. Could you share the script? Thank you very much!
