### ISSUE TITLE
Whether a local pdb file as input possible?

### ISSUE THREAD

**Issue by DaHenz** [LPDI-EPFL/masif#44]
Hi,
If masif could take local pdb files(not deposited in PDB database) as inputs? May by modifying the scripts in data preparation? 
Thanks in advance if anyone could give some suggestions!

**Comment by Lizeerd** [comment]
hi @DaHenz , i have the need too, have get this solved?

**Comment by johnnytam100** [comment]
Same question here!

**Comment by Lsz-20** [comment]
The same quesion
