### ISSUE TITLE
MaSIF_search usage

### ISSUE THREAD

**Issue by xiaolinpan** [LPDI-EPFL/masif#60]
Many thanks for your open-source code. MaSIF is an amazing project for protein-protein interaction prediction and I want to apply it in my study. 

I have some questions about MaSIF.

If I have an in-house protein database, could you tell me how to create the patches from the database of the in-house proteins? How to search the binders by MaSIF_search? Do you have a tutorial for it?

**Comment by Lsz-20** [comment]
same question
