### ISSUE TITLE
Issue with opening PLY files in the latest version of PyMOL

### ISSUE THREAD

**Issue by YFeri** [LPDI-EPFL/masif#62]
Hello!

I'm encountering an issue when attempting to open PLY files in the latest version of PyMOL. Despite confirming that I have the most up-to-date PyMOL version, I'm unable to import the PLY package. The specific error messages I'm receiving are:
Error messages: ModuleNotFoundError: No module named 'loadPLY'.
Plugin installation also failed with error: no module named 'loadPLY'.
I'm currently using PyMOL version 2.5 on Ubuntu.

Could you please provide guidance on how to resolve this problem? Alternatively, if there's an alternative method to view my outputs, I would greatly appreciate any suggestions.

Thank you for your assistance in resolving this issue.

**Comment by Abhishaike** [comment]
Having this same error

**Comment by Abhishaike** [comment]
This fixes it: https://github.com/LPDI-EPFL/masif/issues/15

**Comment by YFeri** [comment]
@Abhishaike  thank you for your help, it solved my problem
