### ISSUE TITLE
why (1 - auc_roc) 

### ISSUE THREAD

**Issue by raoufkeskes** [LPDI-EPFL/masif#64]
Hello, 

I was reading the masif_ppi_search training code  [train_ppi_search.py](https://github.com/LPDI-EPFL/masif/blob/2a370518e0d0d0b0d6f153f2f10f6630ae91f149/source/masif_modules/train_ppi_search.py)
and I realized that during the training you consider **1 - AUCROC**  rather than simply  **AUCROC** as the following 
```
def compute_roc_auc(pos, neg):
    labels = np.concatenate([np.ones((len(pos))), np.zeros((len(neg)))])
    dist_pairs = np.concatenate([pos, neg])
    return metrics.roc_auc_score(labels, dist_pairs)
```

then,

```
roc_auc = 1 - compute_roc_auc(iter_pos_score, iter_neg_score)
val_auc = 1 - compute_roc_auc(pos_dists, neg_dists)
test_auc = 1 - compute_roc_auc(pos_dists, neg_dists)
```
so please why do you reverse the aucroc  ?

**Comment by YAndrewL** [comment]
Hi @raoufkeskes , the same question, did you solve this?

**Comment by raoufkeskes** [comment]
Hello @YAndrewL 


Yes I solved it ! 

because the ROC metric expects  **similarity/affinity**   the higher the value the better the it is  
However, here we work with **distances**   the lower the value the better the it is   

computing a ROC on affinities is equivalent to compute  1 - ROC on distances  


> Hi @raoufkeskes , the same question, did you solve this?

**Comment by YAndrewL** [comment]
> Hello @YAndrewL
> 
> Yes I solved it !
> 
> because the ROC metric expects **similarity/affinity** the higher the value the better the it is However, here we work with **distances** the lower the value the better the it is
> 
> computing a ROC on affinities is equivalent to compute 1 - ROC on distances
> 
> > Hi @raoufkeskes , the same question, did you solve this?

Thank you so much!

**Comment by raoufkeskes** [comment]
you are welcome
