### ISSUE TITLE
second_stage_alignment_nn.py error

### ISSUE THREAD

**Issue by AthenACHY** [LPDI-EPFL/masif#8]
Hi there,
I am trying to see if I can train the ppi-search model and use it for new predictions. However, when I was following the instruction and run ./second_stage_masif.sh 100 there is en error message from python 3. 

File "/masif/source//masif_ppi_search/second_stage_alignment_nn.py", line 114, in <module>
    read_point_cloud(
NameError: name 'read_point_cloud' is not defined

Would you mind letting me know how to fix it?
Also, would you mind kindly describing how to prepare my own data ( I have some docking models from Rosetta) as I  would like to use them for the ppi_search.
Thanks.

**Comment by pablogainza** [comment]
Hi ! Sorry for the late response. I tried to reproduce the error but I'm not getting it. Did you run this from the /masif/comparison/masif_ppi_search directory? 

Did you do a git pull afterwards?

**Comment by AthenACHY** [comment]
Hey there,
I think it runs fine now after I updated my version with git pull 2 weeks ago. Thanks
